# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_version', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('received', models.CharField(blank=True, max_length=255, null=True)),
                ('references', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('x_sender', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('x_virus_scanned', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
